name: nganjuk_discover
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  firebase_auth: ^4.7.0
  firebase_core: ^2.15.0
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.7
  fluttertoast: ^8.2.2
  get: ^4.6.5
  google_fonts: ^5.1.0
  google_sign_in: ^6.1.4
  lottie: ^2.4.0
  page_transition: ^2.0.9
  smooth_page_indicator: ^1.1.0
  tuple: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
  - assets/gambar/
  - assets/lottie/
  uses-material-design: true
